apiVersion: v1
kind: ServiceAccount
metadata:
  name: gen-ai-ksa
  namespace: gen-ai-api-np
  annotations:
    iam.gke.io/gcp-service-account: gen-ai-gsa@cdo-gen-ai-island-np-204b23.iam.gserviceaccount.com