apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: unicorn-brain-hpa
  namespace: gen-ai-api-pr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gen-ai-api-pr
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70