import os

os.environ["OPENAI_API_KEY"]="invalid-key"
os.environ["AZURE_OPENAI_API_TYPE"]="azure"
os.environ["AZURE_OPENAI_API_VERSION"]=""
os.environ["AZURE_OPENAI_API_BASE"]=""
os.environ["AZURE_DEPLOYMENT_NAME"]=""
os.environ["AZURE_EMBEDDING_DEPLOYMENT_NAME"]=""
os.environ["AZURE_OPENAI_API_KEY"]=""

from fastapi.openapi.utils import get_openapi
from main import app
import json

with open('./docs/openapi.json', 'w') as f:
    # This is the default openapi.json generated by FastAPI
    swagger_json = get_openapi(
        title=app.title,
        version=app.version,
        openapi_version=app.openapi_version,
        description=app.description,
        routes=app.routes,
    )

    # Add servers to the openapi.json
    swagger_json['servers'] = [
        {
            "url": "https://ai-np.cloudapps.telus.com/gen-ai-api"
        },
        {
            "url": "https://ai.cloudapps.telus.com/gen-ai-api"
        }   
    ]
    
    # Tried this out but was not able to get it to work because of CORS issues with Auth server
    # swagger_json['components']['securitySchemes'] = {
    #   "testSecurity": {
    #     "type": "oauth2",
    #     "flows": {
    #       "clientCredentials": {
    #         "tokenUrl": "https://apigw-st.telus.com/st/token"
    #       }
    #     }
    #   }
    # }

    # Write the updated openapi.json to file
    json.dump(swagger_json, f)