apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-proxy-us-east
  namespace: oai-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-proxy-us-east
  template:
    metadata:
      labels:
        app: oai-proxy-us-east
        serviceLable: this
    spec:
      serviceAccountName: gen-ai-ksa
      containers:
      - name: container
        image: northamerica-northeast1-docker.pkg.dev/cdo-gen-ai-island-np-204b23/applications/oai-proxy:np
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /lstatus
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 15
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /hcstatus
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        env:
        - name: OAI_PROXY_ENV
          value: "np"
        - name: OAI_PROXY_USE_GSM
          value: "true"
        - name: OAI_PROXY_GSM_PROJ
          value: "cdo-gen-ai-island-np-204b23"
        - name: OAI_INSTANCE
          value: "us-east"

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oai-proxy-us-east-hpa
  namespace: oai-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oai-proxy-us-east
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
